# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Pages
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wranders/markdown-to-pages-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

################################################################################
# Copy files to Pages deploy directory                                         #
################################################################################

    # Copy DER-encoded Certificates and DER-encoded CRLs from repository root
    # - run: cp *.{crl,crt} dist/

    # Copy DER-encoded Certificates and DER-encoded CRLs from subdirectory
    # - run: cp subdirectory/*.{crl,crt} dist/
    
    # Copy Pages CNAME file to the Pages directory
    # - run: cp CNAME dist/

################################################################################
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
